{
 "title": "Project 2 Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(.90,sum(rate(flask_http_request_duration_seconds_bucket{job=\"ec2\"}[1m])) by (le,method))"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "1 - ((1 - (sum(increase(flask_http_request_total{job=\"ec2\", status=~\"2..\"}[7d])) by (method)) /  sum(increase(flask_http_request_total{job=\"ec2\"}[7d])) by (method)) / (1 - .80))"
    }
   ]
  },
  {
   "title": "Throughput RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{status=~\"2..\"}[1m]))"
    }
   ]
  },
  {
   "title": "Availability %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{instance=\"3.139.70.161:80\",status=~\"2..\"})/sum(flask_http_request_total{instance=\"3.139.70.161:80\"})"
    }
   ]
  }
 ]
}